trigger: none
pr:
  - master

pool:
  vmImage: ubuntu-latest

stages:

  - stage: test
    displayName: 'Testing Scripts'
    jobs:
    - job: test
      steps: 
      - script: echo $BUILD_SOURCEBRANCHNAME
      - script: echo ${BUILD_SOURCEBRANCHNAME}.sql