trigger:
  - master
pr: none

pool:
  vmImage: ubuntu-latest
 
stages:

  - stage: Build
    displayName: 'Building Liquibase Artifact'
    dependsOn: PreBuildCheck
    jobs:
    - job: Build
      steps:
      - publish: $(Agent.BuildDirectory)/s/
        artifact: changelogs
